on:
  push:
    # run only against tags
    tags:
      - '*'

permissions:
  contents: write
  # packages: write
  # issues: write

name: goreleaser

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch source
        id: git_fetch
        run: git fetch --force --tags
      - name: Setup Go
        id: setup_go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      - uses: goreleaser/goreleaser-action@v4
        name: Run Go Releaser
        id: run_goreleaser
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
